# Generated by Django 5.0.6 on 2024-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=50)),
                ('service_date', models.DateField()),
                ('request', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
