# Generated by Django 5.0.6 on 2024-06-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0002_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
